# Generated by Django 4.2.6 on 2024-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Of User')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
                ('usertype', models.CharField(default='U', max_length=5)),
            ],
        ),
    ]
