# Generated by Django 4.2.6 on 2024-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Of Book')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publication_date', models.DateField()),
                ('stock_quantity', models.IntegerField()),
                ('language', models.CharField(default='English', max_length=20)),
                ('publisher', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(default='1.png', upload_to='book_covers')),
            ],
        ),
    ]
