# Generated by Django 4.2.6 on 2024-01-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publidate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
