# Generated by Django 4.2.6 on 2024-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart_cartproduct_orders_delete_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
