# Generated by Django 4.2.6 on 2024-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isdelete',
            field=models.BooleanField(default=True),
        ),
    ]
